### ISSUE TITLE
Review kodu przez Pull request

### ISSUE THREAD

**Issue by alien11689** [pokemzok/parkandrest#1]
Hej,
czy mógłbyś zrobić z Twojego brancha Pull request? Tak jak to jest w masterze jest trudniejsze do przejrzenia.

**Comment by pokemzok** [comment]
Hej,

zrobione, aktualnie master posiada tylko Readme, natomiast wszystkie zmiany są na branchu o nazwie pull-request-branch. Jeśli efekt miał być inny daj mi znać.
